parameters:
  - name: DependsOn
    type: string
    default: ''

  - name: ShouldPublish
    type: boolean
    default: false

jobs:
- job: WindowsBuild
  displayName: Windows Build
  ${{ if ne(parameters.DependsOn, '') }}:
    dependsOn: ${{ parameters.DependsOn }}
  ${{ if ne(parameters.DependsOn, '') }}:
    condition: succeeded()
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Win32_X64Debug:
        BuildType: Debug
        BuildSystem: Win32
        BuildArch: x64
      Win32_X64Release:
        BuildType: Release
        BuildSystem: Win32
        BuildArch: x64
      Win32_X86Debug:
        BuildType: Debug
        BuildSystem: Win32
        BuildArch: x86
      Win32_X86Release:
        BuildType: Release
        BuildSystem: Win32
        BuildArch: x86
  steps:
    - checkout: self
      clean: false
      submodules: false

    - script: choco install ninja
      displayName: Install Ninja

    - task: BatchScript@1
      displayName: Setup Visual C++ Environment
      inputs:
        filename: .ado\vcenv.bat
        modifyEnvironment: true

    - task: CMake@1
      displayName: Generate Ninja scripts
      inputs:
        workingDirectory: $(Build.BinariesDirectory)/$(BuildType)/$(BuildSystem)/$(BuildArch)
        cmakeArgs: -G Ninja -DCMAKE_BUILD_TYPE=$(BuildType) -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION=$(BuildWindowsSDK) $(Build.SourcesDirectory)

    - task: CMake@1
      displayName: Build
      inputs:
        workingDirectory: $(Build.BinariesDirectory)/$(BuildType)/$(BuildSystem)/$(BuildArch)
        cmakeArgs: --build .

    - task: CMake@1
      displayName: Stage built files
      inputs:
        workingDirectory: $(Pipeline.Workspace)
        cmakeArgs: --install $(Build.BinariesDirectory)/$(BuildType)/$(BuildSystem)/$(BuildArch) --prefix dist --component dist

    - script: ManifestTests
      displayName: Tests - Manifest
      workingDirectory: $(Pipeline.Workspace)/dist/$(BuildType)/$(BuildSystem)/$(BuildArch)

    - task: PublishPipelineArtifact@1
      displayName: Publish build artifact
      condition: ${{ parameters.ShouldPublish }}
      inputs:
        path: $(Pipeline.Workspace)/dist
        artifactName: Windows-$(BuildType)-$(BuildArch)
