name: Build.$(Date:yyyy-MM-dd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master

pr: none

variables:
  - template: variables.yml

stages:
  - stage: Build
    jobs:
      - job: WindowsBuild
        displayName: Windows Build
        strategy:
          matrix:
            X64Debug:
              BuildConfiguration: Debug
              BuildPlatform: x64
            X64Release:
              BuildConfiguration: Release
              BuildPlatform: x64
            X86Debug:
              BuildConfiguration: Debug
              BuildPlatform: x86
            X86Release:
              BuildConfiguration: Release
              BuildPlatform: x86
        pool:
          vmImage: 'windows-2019'
        timeoutInMinutes: 30
        cancelTimeoutInMinutes: 2
        steps:
          - checkout: self
            clean: false
            submodules: false

          - template: templates/windows-build.yml

          - template: templates/windows-publish-build-artifact.yml

  - stage: Release
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: 'windows-2019'
    jobs:
      - job: BeachBallRelease
        displayName: BeachBall Release
        timeoutInMinutes: 15
        steps:
          - checkout: self
            clean: true
            submodules: false
            persistCredentials: true

          - task: CmdLine@2
            displayName: Configure git user/email
            inputs:
              script: |
                git config --global user.email "53619745+rnbot@users.noreply.github.com"
                git config --global user.name "React-Native-Windows Bot"

          - script: yarn install --frozen-lockfile
            displayName: Install yarn packages

          - script: yarn run beachball publish --no-publish --message "Beachball Publish (no NPM) ***NO_CI***" --yes
            displayName: Beachball publish (no NPM)

      - job: PublishNuGetPackage
        displayName: Publish NuGet package
        dependsOn: BeachBallRelease
        condition: succeeded()
        timeoutInMinutes: 15
        steps:
          - checkout: self
            clean: false
            submodules: false

          - template: templates/download-and-stage-artifact.yml
            parameters:
              Artifact: Windows-Debug-x86

          - template: templates/download-and-stage-artifact.yml
            parameters:
              Artifact: Windows-Release-x86

          - template: templates/download-and-stage-artifact.yml
            parameters:
              Artifact: Windows-Debug-x64

          - template: templates/download-and-stage-artifact.yml
            parameters:
              Artifact: Windows-Release-x64

          - task: CopyFiles@2
            displayName: Stage headers, nuspec
            inputs:
              targetFolder: $(Build.ArtifactStagingDirectory)
              contents: |
                Continuity.nuspec
                include/**

          - task: NuGetToolInstaller@1

          - script: node -p "'##vso[task.setvariable variable=PackageVersion]'+require('./package.json').version"
            displayName: Read package.json version
            workingDirectory: $(Build.SourcesDirectory)

          - script: nuget pack Continuity.nuspec -Properties "commit=$(Build.SourceVersion);id=$(NugetArtifactId);version=$(PackageVersion)" -Verbosity detailed -NonInteractive
            displayName: Create NuGet package
            workingDirectory: $(Build.ArtifactStagingDirectory)

          - task: NuGetAuthenticate@0
            displayName: 'NuGet authentication'

          - task: NuGetCommand@2
            displayName: 'Push to react-native feed'
            inputs:
              command: push
              packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg'
              publishVstsFeed: 'b9acb0c2-0443-4db3-8809-50f5d72408f9' # react-native feed
