name: PR.$(Date:yyyy-MM-dd).$(Rev:r)

trigger: none
pr:
  - master

variables:
  - template: variables.yml

jobs:
  - job: ChangeLog
    displayName: Change Log
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30

    steps:
      - checkout: self
        clean: false
        submodules: false

      - script: yarn
        displayName: Install packages

      - script: yarn run check
        displayName: Check for change files ('yarn run change' if this fails)

  - job: WindowsBuild
    displayName: Windows Build
    dependsOn: ChangeLog
    condition: succeeded()
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 2
    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/windows-build.yml
